USE ROLE ACCOUNTADMIN;

CREATE OR REPLACE DATABASE EDW_2_DB;
CREATE OR REPLACE SCHEMA EDW_2_DB.REASONING;

CREATE OR REPLACE WAREHOUSE EDW_2_WH
WAREHOUSE_SIZE = 'SMALL'
AUTO_SUSPEND = 60
AUTO_RESUME = TRUE;

USE DATABASE EDW_2_DB;
USE SCHEMA REASONING;
USE WAREHOUSE EDW_2_WH;
