CREATE OR REPLACE VIEW EDW_2_DB.PUBLIC.PROFIT_TREND AS
SELECT
    QUARTER,
    SUM(REVENUE) AS TOTAL_REVENUE,
    SUM(COST) AS TOTAL_COST,
    SUM(REVENUE - COST) AS TOTAL_PROFIT
FROM EDW_2_DB.PUBLIC.REVENUE_DATA
GROUP BY QUARTER
ORDER BY QUARTER;
