USE DATABASE EDW_2_DB;
USE SCHEMA REASONING;

-- Time trend
CREATE OR REPLACE VIEW V_REVENUE_BY_QUARTER AS
SELECT
    QUARTER,
    SUM(REVENUE) AS TOTAL_REVENUE,
    SUM(COST) AS TOTAL_COST,
    SUM(REVENUE - COST) AS TOTAL_PROFIT
FROM REVENUE_TABLE
GROUP BY QUARTER
ORDER BY QUARTER;

-- Region trend
CREATE OR REPLACE VIEW V_REVENUE_BY_REGION AS
SELECT
    QUARTER,
    REGION,
    SUM(REVENUE) AS TOTAL_REVENUE
FROM REVENUE_TABLE
GROUP BY QUARTER, REGION;

-- Product trend
CREATE OR REPLACE VIEW V_REVENUE_BY_PRODUCT AS
SELECT
    QUARTER,
    PRODUCT,
    SUM(REVENUE) AS TOTAL_REVENUE
FROM REVENUE_TABLE
GROUP BY QUARTER, PRODUCT;
