-- 03_semantic_views.sql
-- Create semantic views the Streamlit app can query

USE DATABASE EDW_2_DB;
USE SCHEMA REASONING;

-- 1) Quarter-level summary (this is the one your Streamlit app uses)
CREATE OR REPLACE VIEW V_REVENUE_BY_QUARTER AS
SELECT
    QUARTER,
    SUM(REVENUE)              AS TOTAL_REVENUE,
    SUM(COST)                 AS TOTAL_COST,
    SUM(REVENUE - COST)       AS TOTAL_PROFIT
FROM REVENUE_TABLE
GROUP BY QUARTER
ORDER BY QUARTER;

-- 2) Optional: region-level breakdown (useful later)
CREATE OR REPLACE VIEW V_REVENUE_BY_REGION AS
SELECT
    QUARTER,
    REGION,
    SUM(REVENUE)        AS TOTAL_REVENUE,
    SUM(COST)           AS TOTAL_COST,
    SUM(REVENUE - COST) AS TOTAL_PROFIT
FROM REVENUE_TABLE
GROUP BY QUARTER, REGION
ORDER BY QUARTER, REGION;

-- 3) Optional: product-level breakdown (useful later)
CREATE OR REPLACE VIEW V_REVENUE_BY_PRODUCT AS
SELECT
    QUARTER,
    PRODUCT,
    SUM(REVENUE)        AS TOTAL_REVENUE,
    SUM(COST)           AS TOTAL_COST,
    SUM(REVENUE - COST) AS TOTAL_PROFIT
FROM REVENUE_TABLE
GROUP BY QUARTER, PRODUCT
ORDER BY QUARTER, PRODUCT;
