USE ROLE ACCOUNTADMIN;
USE WAREHOUSE EDW_COMPUTE_WH;

-- 1. Core DB + schema
CREATE DATABASE IF NOT EXISTS EDW_2_DB;
USE DATABASE EDW_2_DB;
CREATE SCHEMA IF NOT EXISTS REASONING;
USE SCHEMA REASONING;

-- 2. Base table
CREATE OR REPLACE TABLE REVENUE_TABLE (
    QUARTER STRING,
    REGION  STRING,
    PRODUCT STRING,
    REVENUE NUMBER,
    COST    NUMBER
);

TRUNCATE TABLE REVENUE_TABLE;

INSERT INTO REVENUE_TABLE (QUARTER, REGION, PRODUCT, REVENUE, COST) VALUES
    ('2024-Q2', 'West', 'Product A', 180000, 120000),
    ('2024-Q2', 'East', 'Product B', 140000, 100000),
    ('2024-Q3', 'West', 'Product B', 490000, 300000),
    ('2024-Q3', 'East', 'Product A', 310000, 210000),
    ('2024-Q4', 'West', 'Product A', 300000, 190000),
    ('2024-Q4', 'East', 'Product B', 200000, 140000);

-- 3. Views used by the app
CREATE OR REPLACE VIEW V_REVENUE_BY_QUARTER AS
SELECT
    QUARTER,
    SUM(REVENUE)              AS TOTAL_REVENUE,
    SUM(COST)                 AS TOTAL_COST,
    SUM(REVENUE - COST)       AS TOTAL_PROFIT
FROM REVENUE_TABLE
GROUP BY QUARTER
ORDER BY QUARTER;

CREATE OR REPLACE VIEW V_REVENUE_BY_REGION AS
SELECT
    QUARTER,
    REGION,
    SUM(REVENUE)        AS TOTAL_REVENUE,
    SUM(COST)           AS TOTAL_COST,
    SUM(REVENUE - COST) AS TOTAL_PROFIT
FROM REVENUE_TABLE
GROUP BY QUARTER, REGION
ORDER BY QUARTER, REGION;

CREATE OR REPLACE VIEW V_REVENUE_BY_PRODUCT AS
SELECT
    QUARTER,
    PRODUCT,
    SUM(REVENUE)        AS TOTAL_REVENUE,
    SUM(COST)           AS TOTAL_COST,
    SUM(REVENUE - COST) AS TOTAL_PROFIT
FROM REVENUE_TABLE
GROUP BY QUARTER, PRODUCT
ORDER BY QUARTER, PRODUCT;

-- Optional sanity check
SELECT * FROM V_REVENUE_BY_QUARTER;
SELECT * FROM V_REVENUE_BY_REGION;
SELECT * FROM V_REVENUE_BY_PRODUCT;